# -*- coding: utf-8 -*-
"""CSC110_YOLO_LAB  Israel Praise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgtjoAchd4mLAqWu-qHaeAvY4KhqIGqP
"""

!pip install ultralytics -q

from google.colab import files
uploaded = files.upload()

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model("traffic light 1.jpg")

print("\n========== DETECTION RESULTS ==========")

boxes = results[0].boxes
if len(boxes) == 0:
    print("No objects were detected in the image.")
else:
    print(f"Number of objects detected: {len(boxes)}\n")

print("Detected Objects:")
for r in results:
    for box in r.boxes:
        class_id = int(box.cls)
        class_name = model.names[class_id]
        confidence = box.conf.item()
        xyxy = box.xyxy.cpu().numpy().flatten().tolist()
        print(f"  Class: {class_name}, Confidence: {confidence:.2f}, BBox: {xyxy}")